spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mypass
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  error:
    include-message: always
    include-binding-errors: always


jwt:
  key: F6B7C207C16A7D5090446647407C9C4349D0FC24252250DBDF3A064002BEBFC6

#
#logging:
#  level:
#    root: DEBUG